---
- name: "Download and unpack latest wordpress"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_domain }}"
    remote_src: yes
    creates: "/var/www/{{ http_domain }}/wordpress"

- name: "Set owner"
  file:
    path: "/var/www/{{ http_domain }}"
    state: directory
    recurse: yes
    owner: "{{ apache_run_user }}"
    group: www-data

- name: "Set permissions dirs"
  shell: "/usr/bin/find /var/www/{{ http_domain }}/wordpress/ -type d -exec chmod 750 {} \\;"

- name: "Set permissions files"
  shell: "/usr/bin/find /var/www/{{ http_domain }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: "Setup wp-config"
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/{{ http_domain }}/wordpress/wp-config.php"
